const products = [
    {
        id: 1,
        name: 'Sanitizer Gel',
        price: 50,
        description: 'Germs are everywhere! They can get onto hands and items we touch during daily activities and make us sick. Cleaning hands at key times with soap and water or hand sanitizer that contains at least 60% alcohol is one of the most important steps you can take to avoid getting sick and spreading germs to those around you.',
        totalBuy: 333,
        img: 'https://i.ibb.co/hXMcc4M/5-14-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 2,
        name: 'Vitamin C table',
        price: 60,
        description: 'Ascorbic acid (vitamin C) is used to prevent or treat low levels of vitamin C in people who do not get enough of the vitamin from their diets. Most people who eat a normal diet do not need extra ascorbic acid. Low levels of vitamin C can result in a condition called scurvy.',
        totalBuy: 233,
        img: 'https://i.ibb.co/R66QLg4/5-15-1000x1000.jpg',
        rating: 4,
        brand: "Dr. Care",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 3,
        name: 'Liquid Sanitizer',
        price: 70,
        description: 'Germs are everywhere! They can get onto hands and items we touch during daily activities and make us sick. Cleaning hands at key times with soap and water or hand sanitizer that contains at least 60% alcohol is one of the most important steps you can take to avoid getting sick and spreading germs to those around you.',
        totalBuy: 340,
        img: 'https://i.ibb.co/K9RZwCc/shop-5-13-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 4,
        name: 'Facial Tissue',
        price: 30,
        description: 'In addition to makeup and beauty, facial tissues are one of those convenient products that can be used for various odds and ends, making them a handy item to have around the office. Tissues are particularly useful for quick cleanups and spills as well as dusting, and can be used as padding for delicate items.',
        totalBuy: 733,
        img: 'https://i.ibb.co/SvZP6BR/5-16-1000x1000.jpg',
        rating: 4,
        brand: "Accu-Chek",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 5,
        name: 'Vitamin D3',
        price: 90,
        description: 'Vitamin D3 offers many health benefits. It is known to help strengthen bones and muscles, boost immunity, increase mood, have anti-inflammatory effects, and improve heart function',
        totalBuy: 820,
        img: 'https://i.ibb.co/B2tpNFJ/shop-4-10-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 6,
        name: 'Folic Acid',
        price: 89,
        description: 'Folic acid helps make healthy red blood cells, which carry oxygen around the body. If we do not have enough folic acid, the body can make abnormally large red blood cells that do not work properly. This causes folate deficiency anaemia, which can cause tiredness and other symptoms',
        totalBuy: 500,
        img: 'https://i.ibb.co/LSVQ02J/shop-4-9-1000x1000.jpg',
        rating: 4,
        brand: "Dr. Care",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 7,
        name: 'N95 Face Mask',
        price: 55,
        description: 'N95 respirators and surgical masks are examples of personal protective equipment that are used to protect the wearer from particles or from liquid contaminating the face. The Centers for Disease Control and Prevention (CDC) National Institute for Occupational Safety and Health (NIOSH) also regulates N95 respirators.',
        totalBuy: 890,
        img: 'https://i.ibb.co/W3jjNqk/shop-5-1-1000x1000.jpg',
        rating: 5,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 8,
        name: 'Hand Gloves',
        price: 65,
        description: 'It is important to wear gloves when working with hazardous chemicals and other materials because they protect our hands from infection and contamination. ... Rubber gloves protect against mild corrosive material. Neoprene gloves protect against most solvents, oils, and mild corrosive materials.',
        totalBuy: 450,
        img: 'https://i.ibb.co/hW2W4wt/shop-5-6-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 9,
        name: 'Zinc Tablet',
        price: 50,
        description: 'Zinc helps keep your immune system strong. Because it is necessary for immune cell function and cell signaling, a deficiency can lead to a weakened immune response. Zinc supplements stimulate particular immune cells and reduce oxidative stress.',
        totalBuy: 441,
        img: 'https://i.ibb.co/T8qrXsX/5-19-1000x1000.jpg',
        rating: 4,
        brand: "Dr. Care",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 10,
        name: 'Vitamin B12',
        price: 54,
        description: 'Vitamin B12 is a nutrient that helps keep your body blood and nerve cells healthy and helps make DNA, the genetic material in all of your cells. Vitamin B12 also helps prevent megaloblastic anemia, a blood condition that makes people tired and weak.',
        totalBuy: 220,
        img: 'https://i.ibb.co/C1Q3TZt/shop-4-7-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 11,
        name: 'Object Thermometer',
        price: 350,
        description: 'Infrared thermometers are used to measure the temperature of an object from a safe distance. Infrared thermometers provide temperature readings based on the thermal radiations released by the object. Due to the umpteen advantages that these thermometers offer, making them one of the essential medical supplies.',
        totalBuy: 600,
        img: 'https://i.ibb.co/hBDZSXQ/shop-4-4-1-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
    {
        id: 12,
        name: 'Digital BP Monitor',
        price: 250,
        description: 'Many people monitor their blood pressure at home. They often do this to manage or treat a certain health condition. If you monitor your blood pressure at home, keep a record, or log, of the measurements. The record shows your doctor how your blood pressure changes throughout the day.',
        totalBuy: 600,
        img: 'https://i.ibb.co/fD0S6yT/5-17-1000x1000.jpg',
        rating: 4,
        brand: "Staedtler",
        color: "Black, Blue",
        material: 'Plastic',
        productType: 'Medical',
    },
]